---
# tasks file for hadoop
 - import_tasks: docker_install.yml
   tags:
    - install_docker

 - import_tasks: docker_image_pull.yml
   tags: 
    - pull_image_centos

 - import_tasks: docker_build_image.yml
   tags:
    - build_image_apache

 - import_tasks: docker_run.yml
   tags:
    - run_apache_container
